version: "3.8"
networks: 
  crud-greeter-network:
    external: false
    name: crud-greeter-network
services:
  crud-greeter:
    image: crud-greeter
    networks: 
      - crud-greeter-network
    ports:
      # extern:intern
      - 3000:3000
    environment:
      - IS_DOCKER=true
      - AUTH_TOKEN=your-super-secret-token
      - PORT=3000